# Site settings
title: Little Saxony Tales
SEOTitle: Tianlin He | Little Saxony Tales
header-img: img/post-bg-desk-short.jpg
email: tinaho_ok@hotmail.com
description: "相信未來熱愛生命"
keyword: "Tianlin He, Sweden, tianlinhe, Germany, 德國, PhD, 博士"
url: "http://tianlinhe.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/tianlinhe/tianlinhe.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "此處禁鑽牛角尖"
sidebar-avatar: /img/about-TL-gotland.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

<!-- Begin Mailchimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://hotmail.us7.list-manage.com/subscribe/post?u=b1c9a5c1c3d2d33c7e2a24b79&amp;id=651287e3c1" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<label for="mce-EMAIL">Subscribe</label>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_b1c9a5c1c3d2d33c7e2a24b79_651287e3c1" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->

# Markdown rendering
markdown: kramdown

# SNS settings
RSS: false
# weibo_username:     qiubaiying
#zhihu_username:     qiubaiying
github_username:    tianlinhe
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying
#instagram_username:  tinaho_ok




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
#Disqus（https://disqus.com/）
disqus_username: tianlinhe

# Gitalk
#gitalk:
  #enable: true    #是否开启Gitalk评论
  #clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  #clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  #repo: qiubaiying.github.io    #仓库名称
  #owner: qiubaiying    #github用户名
  #admin: qiubaiying
  #distractionFreeMode: true #是否启用类似FB的阴影遮罩

# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
google_analytics: UA-135895652-1            # Format: UA-xxxxxx-xx
#ga_domain: tianlin.auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
    #{
        #title: "WY",
        #href: "http://zhengwuyang.com"
    #},{
        #title: "简书·BY",
        #href: "http://www.jianshu.com/u/e71990ada2fd"
    #},{
        #title: "Apple",
        #href: "https://apple.com"
    #},{
        #title: "Apple Developer",
        #href: "https://developer.apple.com/"
    #}
#]
